### ISSUE TITLE
UpdateAsync does not yield

### ISSUE THREAD

**Issue by Nezuo** [buildthomas/MockDataStoreService#18]
UpdateAsync only yields if the transform function returns nil which isn't accurate behavior.

https://github.com/buildthomas/MockDataStoreService/blob/4ebdaf42d12576decae32741e2a1d8d7c3501b39/lib/MockDataStoreService/MockOrderedDataStore.lua#L367

**Comment by buildthomas** [comment]
I think you are misinterpreting this, there's another yield here:
https://github.com/buildthomas/MockDataStoreService/blob/4ebdaf42d12576decae32741e2a1d8d7c3501b39/lib/MockDataStoreService/MockOrderedDataStore.lua#L393

What you are highlighting is an edge case that should return early, but since it simulates a remote call, it should also yield before returning there.
