### ISSUE TITLE
Split MockDataStoreService into several files

### ISSUE THREAD

**Issue by buildthomas** [buildthomas/MockDataStoreService#2]
- MockDataStoreService
- MockGlobalDataStore
- MockOrderedDataStore
- MockDataStorePages
- MockDataStoreUtils (all utility functions go here)
- MockDataStoreConstants (all constants go here)

Might require an extra class that acts as the master of all data/interfaces and that MockDataStoreService/MockGlobalDataStore/MockOrderedDataStore accesses this instead of owning the data itself, otherwise it requires adding extra methods to these classes which would clash with the design principle of sticking to the Roblox API.

**Comment by Validark** [comment]
My vote for the Github file layout:
![image](https://user-images.githubusercontent.com/15217173/43640279-f7394c4a-96e4-11e8-8dea-056a060841ff.png)

What it looks like in studio:
![image](https://user-images.githubusercontent.com/15217173/43640314-1b1c4978-96e5-11e8-88f8-3357bee562ef.png)

I would like `DataStoreService` to be the top `ModuleScript` so this script can be a single "package" rather than two. That way the developer will know to only (in most cases) interact with the `DataStoreService` library, and it is then much easier to explain:

> Simply use this library in place of game:GetService("DataStoreService") and it will return DataStoreService in a live game and an emulated Lua implementation of MockDataStoreService for testing in Studio.

**Comment by buildthomas** [comment]
Yes, that seems a good way to go about it. I can apply this soon together with #3.

**Comment by buildthomas** [comment]
Resolved!
