### ISSUE TITLE
Yield times are unrealistic

### ISSUE THREAD

**Issue by LucasMZReal** [buildthomas/MockDataStoreService#20]
I refer to a `:UpdateAsync` request which tries to write to the DataStore, not when it returns nil.

I _don't_ know about other requests / scenarios.

So when I was testing it a while back I noticed `:UpdateAsync` calls are unrealistically fast.

In my testing, yield times for a simple table with some small contents when using actual datastores is something like this:

* On Studio: 1.5 - 3.0 seconds;
* In-Game: .3 - .8 seconds:

But when I used this module it took WAYY less than that, something like .02 seconds or close.

This might be what this person referenced here:

https://github.com/buildthomas/MockDataStoreService/issues/18

But I'm not sure.

**Comment by buildthomas** [comment]
The yield times are not meant to be realistic, and can be tuned by the settings file.

What is meant to be simulated here is **when** data stores yield, not exactly trying to mimick how long, since that is highly dependent on the state of the network and on how they are scaling/distributing the data stores back-end at any point in time.
